### ISSUE TITLE
Sparkles unable to create tmpfile

### ISSUE THREAD

**Issue by hhamalai** [CSC-IT-Center-for-Science/spark-analysis#11]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spark_analysis-1.0-py2.7.egg/sparkles/modules/data_import.py", line 146, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/spark_analysis-1.0-py2.7.egg/sparkles/modules/data_import.py", line 118, in main
    hfile = add_all_dates(originalpath)
  File "/usr/local/lib/python2.7/dist-packages/spark_analysis-1.0-py2.7.egg/sparkles/modules/data_import.py", line 15, in add_all_dates
    hfile = NamedTemporaryFile(delete=False, dir='/shared_data/tmp')
  File "/usr/lib/python2.7/tempfile.py", line 462, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)

**Comment by apurvann** [comment]
Done. Waiting for merge. Check b1ba795
